spring:
  liquibase:
    enabled: false
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_practice}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
